services:
  - type: web
    name: bookstore
    env: dotnet
    region: oregon
    buildCommand: dotnet publish -c Release -o publish
    startCommand: dotnet publish/bookstore.dll
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080